### ISSUE TITLE
Thanks for this! Cloudwatch?

### ISSUE THREAD

**Issue by tspicer** [Castaglia/proftpd-mod_statsd#16]
Great work. Are you thinking about extending this pattern to other services like Cloudwatch? Was not sure if you were thinking of this as a general pattern for emitting this data out. 

Thanks again. Will look to put this to use!

**Comment by Castaglia** [comment]
I think that CloudWatch integration would happen within `mod_aws`; that's a better place for this feature request.  The larger question, in my mind, is whether the metrics currently provided by `mod_statsd` are the ones that you'd want to see via CloudWatch?

There're the metrics, and then there is the transport mechanism for those metrics.  CloudWatch, statsd, snmp -- these are all means of _transport_.  I'm happen to work on CloudWatch integration, as long as the metrics are the ones you want.

**Comment by tspicer** [comment]
I agree the right place is your AWS module. Let me look at CW and provide some feedback.

**Comment by Castaglia** [comment]
Closing this ticket, in favor/preference of the ticket for CloudWatch support for `mod_aws`.  Thanks!
